name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Images
        run: |
          docker build kubeflow_pipeline/0_data -t molozise/mnist-pre-data
          docker push molozise/mnist-pre-data
          docker build kubeflow_pipeline/1_validate_data -t molozise/mnist-val-data
          docker push molozise/mnist-val-data
          docker build kubeflow_pipeline/2_train_model -t molozise/mnist-train-model
          docker push molozise/mnist-train-model
          docker build kubeflow_pipeline/3_embedding -t molozise/mnist-embedding
          docker push molozise/mnist-embedding
          docker build kubeflow_pipeline/4_train_faiss -t molozise/mnist-train-faiss
          docker push molozise/mnist-train-faiss
          docker build kubeflow_pipeline/5_analysis_model -t molozise/mnist-analysis
          docker push molozise/mnist-analysis
          docker build kubeflow_pipeline/6_deploy -t molozise/mnist-deploy
          docker push molozise/mnist-deploy

